"use strict";
const M=window.RETRIEVAL_MANIFEST, models=Object.keys(M.models), loaded=window.RETRIEVAL_SCENES=window.RETRIEVAL_SCENES||{};
const state={model:models[0],query:M.queries[0].scene_id,setting:"standard",raster:"landcover",layers:new Set(["B","R","P"]),selected:{top:0,middle:0,bottom:0}};
const $=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)];
function parseHash(){const p=new URLSearchParams(location.hash.slice(1));if(models.includes(p.get("model")))state.model=p.get("model");if(M.queries.some(q=>q.scene_id===p.get("query")))state.query=p.get("query");if(["standard","nonlocal"].includes(p.get("setting")))state.setting=p.get("setting");for(const b of ["top","middle","bottom"]){const n=Number(p.get(b));if(Number.isInteger(n)&&n>=0&&n<10)state.selected[b]=n}}
function saveHash(){const p=new URLSearchParams({model:state.model,query:state.query,setting:state.setting,top:state.selected.top,middle:state.selected.middle,bottom:state.selected.bottom});history.replaceState(null,"","#"+p)}
function loadScene(id){if(loaded[id])return Promise.resolve(loaded[id]);return new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=`assets/scenes/${id}.js`;script.onload=()=>resolve(loaded[id]);script.onerror=()=>reject(new Error(`Missing scene asset ${id}`));document.head.append(script)})}
function candidates(){return M.models[state.model].queries[state.query][state.setting]}
function columns(){const c=candidates(), q={scene_id:state.query,rank:null,similarity:null,distance_m:0};return[{key:"query",title:"Original spatial scene",item:q,strip:null},{key:"most",title:"Most similar",item:c.bands.most[0],strip:null},...['top','middle','bottom'].map(key=>({key,title:key==='top'?'Top band (10)':key==='middle'?'Middle band (10)':'Bottom band (10)',item:c.bands[key][state.selected[key]],strip:c.bands[key]}))]}
function fmt(v,d=2){return v==null?'Unavailable':Number(v).toLocaleString(undefined,{maximumFractionDigits:d})}
function decode(rle){const out=[];for(const [v,n] of rle)for(let i=0;i<n;i++)out.push(v);return out}
function pathSets(geometry){const c=geometry.coordinates,t=geometry.type;if(t==='Point')return[[[c]]];if(t==='MultiPoint')return c.map(p=>[[p]]);if(t==='LineString')return[[c]];if(t==='MultiLineString')return c.map(line=>[line]);if(t==='Polygon')return[c];if(t==='MultiPolygon')return c;return[]}
function drawVector(canvas,scene){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const x=canvas.getContext('2d');x.scale(dpr,dpr);x.fillStyle='#f7f8f4';x.fillRect(0,0,w,h);const sx=w/500,sy=h/500;for(const e of scene.vectors){if(!state.layers.has(e.type))continue;const color=e.type==='B'?'#d5a940':e.type==='R'?'#50616d':'#c33c54';for(const paths of pathSets(e.geometry)){x.beginPath();for(const path of paths){path.forEach((p,i)=>{const px=p[0]*sx,py=h-p[1]*sy;i?x.lineTo(px,py):x.moveTo(px,py)});if(e.type==='B')x.closePath()}if(e.type==='B'){x.fillStyle=color+'99';x.fill('evenodd');x.strokeStyle='#8e7028';x.lineWidth=.7;x.stroke()}else if(e.type==='R'){x.strokeStyle=color;x.lineWidth=1.2;x.stroke()}else{const p=paths[0][0];x.beginPath();x.arc(p[0]*sx,h-p[1]*sy,2,0,Math.PI*2);x.fillStyle=color;x.fill()}}}}
function drawRaster(canvas,scene,min,max){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const x=canvas.getContext('2d');x.scale(dpr,dpr);const r=state.raster==='landcover'?scene.landcover:scene.dem,values=decode(r.rle),rows=r.shape[0],cols=r.shape[1],cw=w/cols,ch=h/rows;for(let i=0;i<values.length;i++){const v=values[i];if(v==null||v===0)x.fillStyle='#e2e5e1';else if(state.raster==='landcover')x.fillStyle=M.render.landcover_colors[v-1];else{x.fillStyle=viridis((v-min)/Math.max(max-min,1e-9))}x.fillRect((i%cols)*cw,Math.floor(i/cols)*ch,Math.ceil(cw+.3),Math.ceil(ch+.3))}}
function viridis(t){t=Math.max(0,Math.min(1,t));const stops=[[68,1,84],[59,82,139],[33,145,140],[94,201,98],[253,231,37]],u=t*(stops.length-1),i=Math.min(stops.length-2,Math.floor(u)),f=u-i;return`rgb(${stops[i].map((v,j)=>Math.round(v+(stops[i+1][j]-v)*f)).join(',')})`}
function list(items){return items.length?items.map(x=>`<li>${x.label}: <b>${x.count}</b></li>`).join(''):'<li>None</li>'}
function columnHTML(col){const item=col.item,meta=item.rank==null?'Fixed P10 query':`Rank ${item.rank.toLocaleString()} · sim ${item.similarity.toFixed(5)} · ${fmt(item.distance_m/1000,2)} km`;const strip=col.strip?`<div class="strip">${col.strip.map((x,i)=>`<button data-band="${col.key}" data-index="${i}" class="${i===state.selected[col.key]?'selected':''}" title="Rank ${x.rank} · ${x.scene_id}"><canvas data-thumb="${x.scene_id}"></canvas><span>#${x.rank}</span></button>`).join('')}</div>`:'<div class="strip-spacer"></div>';return`<section class="column" data-scene="${item.scene_id}"><div class="column-head"><h2>${col.title}</h2><div class="rank-meta">${meta}</div><div class="scene-id">${item.scene_id}<button class="copy" data-copy="${item.scene_id}" title="Copy scene ID">Copy</button></div></div>${strip}<div class="row"><div class="row-title">Vector data</div><div class="map-frame"><canvas class="vector"></canvas><span class="north">N&#8593;</span><span class="scale">200 m</span></div><div class="legend"><span><i class="swatch" style="background:#d5a940"></i>Building</span><span><i class="swatch" style="background:#50616d"></i>Road</span><span><i class="swatch" style="background:#c33c54"></i>POI</span></div></div><div class="row"><div class="row-title">Raster data</div><div class="map-frame"><canvas class="raster"></canvas></div><div class="raster-legend"></div></div><div class="row attributes"><div class="row-title">Attributes & spatial relations</div><div class="loading">Loading scene</div></div></section>`}
function summary(scene){const s=scene.summary,r=s.relations,lc=scene.landcover.composition.map((v,i)=>({label:`LC ${String(i+1).padStart(2,'0')}`,value:v})).sort((a,b)=>b.value-a.value).slice(0,5);return`<div class="summary"><div class="metric"><b>${fmt(s.building_count,0)}</b><span>buildings · ${fmt(s.building_coverage*100,1)}% cover</span></div><div class="metric"><b>${fmt(s.road_segment_count,0)}</b><span>roads · ${fmt(s.road_length_m,0)} m</span></div><div class="metric"><b>${fmt(s.poi_count,0)}</b><span>POIs</span></div><div class="metric"><b>${fmt(scene.dem.mean,1)} m</b><span>DEM ${fmt(scene.dem.min,1)}–${fmt(scene.dem.max,1)} m</span></div></div><div class="relations">${['SN','CNT','WIT','INT','CON'].map(k=>`<div class="relation"><b>${fmt(r[k],0)}</b>${k}</div>`).join('')}</div><details><summary>Detailed summaries</summary><p><b>Location</b> ${scene.district} (${scene.district_id}) · X ${fmt(scene.center[0],1)}, Y ${fmt(scene.center[1],1)}</p><b>POI categories</b><ul class="detail-list">${list(s.poi_categories)}</ul><b>Land cover composition</b><ul class="detail-list">${lc.map(x=>`<li>${x.label}: <b>${fmt(x.value*100,1)}%</b></li>`).join('')}</ul><b>Building use</b><ul class="detail-list">${list(s.building_types)}</ul><b>Building structure</b><ul class="detail-list">${list(s.building_structures)}</ul><b>Road rank</b><ul class="detail-list">${list(s.road_ranks)}</ul></details>`}
async function render(){saveHash();const cols=columns();$('#comparison').innerHTML=cols.map(columnHTML).join('');const q=M.queries.find(x=>x.scene_id===state.query),c=candidates();$('#context').innerHTML=`<span><strong>${M.models[state.model].label}</strong> · ${state.model}</span><span>Query ${q.index}/10 · <strong>${q.district}</strong></span><span>X ${fmt(q.center[0],1)} · Y ${fmt(q.center[1],1)}</span><span>${state.setting==='standard'?'Standard — local candidates allowed':'Non-local — candidates within 2 km excluded'}</span><span><strong>${c.candidate_count.toLocaleString()}</strong> candidates</span>`;$('#status').textContent='Loading scene assets';try{const sceneIds=[...new Set(cols.flatMap(x=>[x.item.scene_id,...(x.strip||[]).map(y=>y.scene_id)]))],sceneValues=await Promise.all(sceneIds.map(loadScene)),sceneMap=Object.fromEntries(sceneValues.map(x=>[x.scene_id,x])),scenes=cols.map(x=>sceneMap[x.item.scene_id]);const validDem=scenes.flatMap(s=>decode(s.dem.rle).filter(v=>v!=null)),min=Math.min(...validDem),max=Math.max(...validDem);all('[data-thumb]').forEach(canvas=>drawVector(canvas,sceneMap[canvas.dataset.thumb]));all('.column').forEach((el,i)=>{const scene=scenes[i];drawVector(el.querySelector('.vector'),scene);drawRaster(el.querySelector('.raster'),scene,min,max);el.querySelector('.attributes').innerHTML=`<div class="row-title">Attributes & spatial relations</div>${summary(scene)}`;if(state.raster==='dem'){el.querySelector('.raster-legend').innerHTML=`<div class="dem-key"></div><div class="legend"><span>${fmt(min,1)} m</span><span style="margin-left:auto">${fmt(max,1)} m</span></div>`}else{const present=scene.landcover.composition.map((v,i)=>({v,i})).filter(x=>x.v>0);el.querySelector('.raster-legend').innerHTML=`<div class="legend">${present.map(x=>`<span title="LC class ${x.i+1}: ${fmt(x.v*100,1)}%"><i class="swatch" style="background:${M.render.landcover_colors[x.i]}"></i>${String(x.i+1).padStart(2,'0')}</span>`).join('')}</div>`}});$('#status').textContent='Evidence ready'}catch(error){$('#status').textContent='Asset error';console.error(error)}}
async function copyText(value){try{await navigator.clipboard.writeText(value)}catch(_){const input=document.createElement('textarea');input.value=value;document.body.append(input);input.select();document.execCommand('copy');input.remove()}}
function setup(){parseHash();const model=$('#model'),query=$('#query');model.innerHTML=models.map(id=>`<option value="${id}">${M.models[id].label} — ${id}</option>`).join('');query.innerHTML=M.queries.map(q=>`<option value="${q.scene_id}">${q.index}. ${q.scene_id} · ${q.district} · ${q.center.map(v=>v.toFixed(1)).join(', ')}</option>`).join('');model.value=state.model;query.value=state.query;all(`input[name=setting]`).forEach(x=>x.checked=x.value===state.setting);model.onchange=()=>{state.model=model.value;render()};query.onchange=()=>{state.query=query.value;render()};all('input[name=setting]').forEach(x=>x.onchange=()=>{state.setting=x.value;render()});all('input[name=raster]').forEach(x=>x.onchange=()=>{state.raster=x.value;render()});all('.checks input').forEach(x=>x.onchange=()=>{x.checked?state.layers.add(x.value):state.layers.delete(x.value);render()});function step(n){state.model=models[(models.indexOf(state.model)+n+models.length)%models.length];model.value=state.model;render()}$('#prevModel').onclick=()=>step(-1);$('#nextModel').onclick=()=>step(1);$('#comparison').onclick=e=>{const b=e.target.closest('[data-band]');if(b){state.selected[b.dataset.band]=Number(b.dataset.index);render()}const c=e.target.closest('[data-copy]');if(c)copyText(c.dataset.copy)};window.onhashchange=()=>{parseHash();model.value=state.model;query.value=state.query;render()};render()}
setup();
