root <- normalizePath(Sys.getenv("FUSE_REPO_ROOT", "../.."), mustWork = TRUE)
test_that("isolated S12 graph has explicit resources and immutable consumer boundaries", {
  old <- setwd(root); on.exit(setwd(old))
  source("R/s12_representation.R")
  expect_true(all(file.exists(s12_source_paths())))
  manifest <- targets::tar_manifest(script = "_targets_representation_comparison.R", fields = tidyselect::everything())
  expect_equal(nrow(manifest), 12L)
  expect_true(all(grepl("^s12_", manifest$name)))
  expect_true(all(vapply(manifest$resources, function(r) identical(r$crew$controller, "controller_05"), logical(1))))
  expect_true(all(c("s12_model_acceptance", "s12_scientific_acceptance") %in% manifest$name))
  expect_silent(targets::tar_validate(script = "_targets_representation_comparison.R"))
  network <- targets::tar_network(script = "_targets_representation_comparison.R", targets_only = TRUE, outdated = FALSE)
  expect_equal(nrow(network$vertices), 12L)
})
test_that("full wrapper fixes terminal and store and requires pilot", {
  text <- paste(readLines(file.path(root, "scripts/run_s12_representation.R")), collapse = "\n")
  expect_match(text, "names = s12_scientific_acceptance", fixed = TRUE)
  expect_match(text, "fuse-s12-representation-alignment", fixed = TRUE)
  expect_match(text, "pilot_receipt_env", fixed = TRUE)
  expect_false(grepl("_targets_evaluation", text, fixed = TRUE))
})

test_that("empty R orchestration requests remain JSON objects", {
  source(file.path(root, "R/s12_representation.R"))
  p <- tempfile(fileext = ".json"); on.exit(unlink(p))
  s12_write_request(list(), p)
  expect_identical(paste(readLines(p), collapse = ""), "{}")
  s12_write_request(list(model = "cmp_A1", spec = list(positions = as.list(0:31))), p)
  r <- jsonlite::read_json(p)
  expect_identical(r$model, "cmp_A1")
  expect_equal(unlist(r$spec$positions), 0:31)
})
