withr::local_dir(normalizePath("../.."))
source("R/b6_stage_b_preparation.R")
testthat::test_that("preparation graph is isolated and CPU-only while method gate is open", {
  x<-targets::tar_manifest(script="_targets_b6_stage_b_preparation.R")
  testthat::expect_length(x$name,6)
  testthat::expect_true(all(startsWith(x$name,"b6b_")))
  g<-targets::tar_network(script="_targets_b6_stage_b_preparation.R")
  testthat::expect_true(igraph::is_dag(igraph::graph_from_data_frame(g$edges)))
  testthat::expect_error(b6b_run("training"),"not TRUE")
  cfg<-yaml::read_yaml("config/b6_stage_b_preparation.yml")
  testthat::expect_false(cfg$full_training_allowed)
  testthat::expect_identical(cfg$outside_node_child_lift,"unresolved_fail_closed")
  targets::tar_validate(script="_targets_b6_stage_b_preparation.R")
})
