s11_fixture_root <- normalizePath(Sys.getenv("FUSE_REPO_ROOT", "../.."), mustWork = TRUE)
source(file.path(s11_fixture_root, "R/scene_descriptors.R"))
rect <- function(x, y, w, h) sf::st_polygon(list(matrix(c(x,y,x+w,y,x+w,y+h,x,y+h,x,y), ncol=2, byrow=TRUE)))
sfc <- function(...) sf::st_sfc(..., crs=5186)

test_that("approved clipped geometry formulas use union, entities, and bbox centers", {
  b <- sfc(rect(0,0,4,2), rect(2,0,4,2))
  r <- sfc(sf::st_linestring(matrix(c(0,0,3,0,3,4), ncol=2, byrow=TRUE)),
           sf::st_linestring(matrix(c(10,0,13,0), ncol=2, byrow=TRUE)))
  p <- sfc(sf::st_point(c(0,0)), sf::st_point(c(0,4)))
  d <- s11_geometry_descriptors(b,r,p)
  expect_equal(d$building_coverage$value, 12/250000)
  expect_equal(d$mean_building_footprint_size$value, 8)
  expect_equal(d$mean_building_compactness$value, 2*pi/9)
  expect_equal(d$building_orientation_dispersion$value, 0, tolerance=1e-14)
  expect_equal(d$road_orientation_dispersion$value, .8, tolerance=1e-14)
  expect_equal(d$mean_road_segment_length$value, 5)
  expect_equal(d$road_density$value, .04)
  expect_equal(d$poi_density$value, 8)
  expect_equal(d$building_location_dispersion$value, 1)
  expect_equal(d$poi_location_dispersion$value, 2)
  reversed <- sfc(sf::st_linestring(matrix(c(3,4,3,0,0,0),ncol=2,byrow=TRUE)), r[[2]])
  expect_equal(s11_road_orientation(reversed)$value, d$road_orientation_dispersion$value)
  # Geometry centroid of this L shape differs from the required bbox center.
  lshape <- sf::st_polygon(list(matrix(c(0,0,4,0,4,1,1,1,1,4,0,4,0,0),ncol=2,byrow=TRUE)))
  expect_equal(s11_location_dispersion(sfc(lshape,rect(4,0,4,4)))$value, 2)
})

test_that("holes and multipart boundaries count in perimeter, not as new entities", {
  hole <- sf::st_polygon(list(rect(0,0,10,10)[[1]], rect(3,3,4,4)[[1]]))
  d <- s11_geometry_descriptors(sfc(hole),sfc(),sfc())
  expect_equal(d$mean_building_compactness$value, 4*pi*84/56^2)
  multi <- sf::st_multipolygon(list(unclass(rect(0,0,4,2)),unclass(rect(10,0,4,2))))
  d <- s11_geometry_descriptors(sfc(multi),sfc(),sfc())
  expect_equal(d$mean_building_footprint_size$value,16)
  expect_equal(d$mean_building_compactness$value,4*pi*16/24^2)
  expect_equal(d$mean_building_footprint_size$total_count,1)
})

test_that("empty, singleton, exact square and substantive near-square are distinct", {
  d <- s11_geometry_descriptors(sfc(),sfc(),sfc())
  expect_equal(d$building_coverage$value,0)
  expect_equal(d$road_density$value,0)
  expect_equal(d$poi_density$value,0)
  expect_null(d$mean_building_compactness$value)
  expect_match(d$building_orientation_dispersion$null_reason,"empty")
  expect_null(s11_building_orientation(sfc(rect(0,0,2,2)))$value)
  expect_equal(s11_building_orientation(sfc(rect(0,0,2,2.001)))$value,0,tolerance=1e-14)
  expect_equal(s11_location_dispersion(sfc(sf::st_point(c(5,7))))$value,0)
  wrong_crs <- sf::st_sfc(rect(0,0,4,2),crs=4326)
  expect_error(s11_geometry_descriptors(wrong_crs,sfc(),sfc()),"CRS")
})

test_that("inverse inclusion, multitype edges and isolates obey D2", {
  e <- data.frame(source_local_entity_id=c(0L,1L,0L,2L),destination_local_entity_id=c(1L,0L,2L,0L),relation_mask=c(9L,9L,2L,4L))
  d <- s11_relation_descriptors(e,0:3)
  expect_equal(d$relation_composition$value,c(1/3,1/3,1/3,0))
  expect_equal(d$mean_relational_degree$value,1)
  expect_equal(unname(d$qc$event_counts),c(1,1,1,0))
  expect_error(s11_relation_descriptors(e[-2,],0:3),"asymmetric")
  expect_error(s11_relation_descriptors(e[-4,],0:3),"inverse")
  expect_error(s11_relation_descriptors(rbind(e,e[1,]),0:3),"duplicate")
  expect_equal(s11_relation_descriptors(e[0,],0:3)$mean_relational_degree$value,0)
  expect_null(s11_relation_descriptors(e[0,],integer())$mean_relational_degree$value)
  expect_null(s11_relation_descriptors(e[0,],0:3)$relation_composition$value)
})

test_that("known-category denominator keeps unknown and missing separate", {
  d <- s11_composition(c("a","b","a",NA,"UNKNOWN"),c("a","b"))
  expect_equal(d$value,c(2/3,1/3)); expect_equal(d$valid_count,3)
  expect_equal(d$missing_count,1); expect_equal(d$unknown_count,1)
  expect_null(s11_composition(character(),c("a","b"))$value)
  p <- data.frame(CLASS_L1_CODE=c("A01","A04","A04"),CLASS_L2_CODE=c("A01","A01","F00"),
                  CLASS_L1_STATE="VALUE",CLASS_L2_STATE=c("VALUE","VALUE","TERMINAL_DASH"))
  expect_equal(s11_poi_l2_keys(p),c("A01/A01","A04/A01",NA))
  lanes <- s11_mean(c(2,4,NA,0,-1),positive=TRUE)
  expect_equal(lanes$value,3); expect_equal(lanes$valid_count,2)
  expect_error(s11_mean(c(1,Inf),TRUE),"NaN")
  entries <- list(list(attribute="A11",category_key="40",source_order=1,source_label="shared",source_code="40",source_codes=list("40")),
                  list(attribute="A11",category_key="42",source_order=2,source_label="shared",source_code="42",source_codes=list("42")))
  resolved <- s11_resolve_categories(c("shared","42","unknown",NA),entries,"A11")
  expect_equal(resolved$value,c(.5,.5))
  expect_equal(resolved$alias_collision_count,1)
  expect_equal(resolved$unknown_count,1)
  expect_equal(resolved$missing_count,1)
})

test_that("valid-area raster weighting and population SD match analytic values", {
  d <- s11_landcover(matrix(c(1,0,0,1),nrow=2),c(1,.5))
  expect_equal(d$value,c(2/3,1/3))
  dem <- s11_dem(c(10,20,-32767),c(1,.5,0))
  expect_equal(dem$mean_elevation$value,40/3)
  expect_equal(dem$elevation_variability$value,sqrt(200/9))
  expect_equal(dem$mean_elevation$valid_weight,1.5)
  expect_null(s11_dem(c(-32767,-32767),c(0,0))$mean_elevation$value)
  expect_equal(s11_dem(10,1)$elevation_variability$value,0)
  expect_error(s11_dem(-32767,1),"supported DEM")
  expect_error(s11_landcover(matrix(c(.1,.2),nrow=2),1),"proportions")
})

test_that("all 22 core descriptor names are exercised and empty records serialize as null", {
  geometry <- s11_geometry_descriptors(sfc(),sfc(),sfc())
  edges <- data.frame(source_local_entity_id=integer(),destination_local_entity_id=integer(),relation_mask=integer())
  relations <- s11_relation_descriptors(edges,integer())[c("relation_composition","mean_relational_degree")]
  semantics <- setNames(rep(list(s11_composition(character(),c("known"))),5),
    c("building_use_composition","building_structure_composition","road_type_composition","road_hierarchy_composition","poi_l2_composition"))
  values <- c(geometry,relations,semantics,list(mean_lane_count=s11_mean(numeric(),TRUE),
    landcover_composition=s11_landcover(matrix(0,nrow=22,ncol=10000),rep(0,10000))),
    s11_dem(rep(-32767,289),rep(0,289)))
  contract <- jsonlite::read_json(file.path(s11_fixture_root,"config/s11_representation_analysis.json"))
  expected <- vapply(contract$descriptors,function(x) x$id,character(1))
  expect_setequal(names(values),expected)
  expect_length(values,22)
  raw <- jsonlite::toJSON(values,auto_unbox=TRUE,null="null",na="null",digits=16)
  readback <- jsonlite::fromJSON(raw,simplifyVector=FALSE)
  expect_null(readback$mean_elevation$value)
  expect_equal(readback$building_coverage$value,0)
  expect_true(nzchar(readback$mean_elevation$null_reason))
  expect_false(grepl("NaN|Infinity",raw))
})
