'use strict';
let C,Q=[],current=0,token=0;const $=id=>document.getElementById(id),fmt=(v,n=4)=>Number(v).toFixed(n),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const filters=[['all','All queries'],['nonempty','Road-nonempty'],['zero','Zero-road ceiling'],['count1','Road count 1–8'],['count9','Road count 9–49'],['count50','Road count 50+'],...['0–50','50–100','100–250','250–500','500+'].map(x=>['length'+x,'Mean parent length '+x+' m']),['disagree','Arms disagree at rank 1'],['gwin','Original wrong, G right'],['pwin','Original wrong, Ppre right'],['failure','Original right, segmented wrong'],['gp','G and Ppre top-10 differ'],['loss','Loss improved, correct rank unchanged'],['gainG','G loss or rank improves'],['gainP','Ppre loss or rank improves']];
const sorts=[['order','Original query order'],['id','Query ID'],['disagreement','Disagreement first'],['roads','Road count ↓'],['length','Mean parent length ↓'],...['Original','G','Ppre'].flatMap((x,i)=>[[`rank${i}`,x+' source rank ↓'],[`score${i}`,x+' source cosine ↑']])];
function match(q,f){let g=C.gallery[q.scene],a=q.arms,o=a[0];if(f==='all')return true;if(f==='nonempty')return g.roads>0;if(f==='zero')return !g.roads;if(f.startsWith('length'))return g.lengthbin===f.slice(6);if(f.startsWith('count'))return g.countbin===({'count1':'1–8','count9':'9–49','count50':'50+'})[f];if(f==='disagree')return new Set(a.map(x=>x.top)).size>1;if(f==='gwin')return o.rank>1&&a[1].rank===1;if(f==='pwin')return o.rank>1&&a[2].rank===1;if(f==='failure')return o.rank===1&&a.slice(1).some(x=>x.rank>1);if(f==='gp')return q.gp_top10_diff;if(f==='loss')return a.slice(1).some(x=>x.loss<o.loss&&x.rank===o.rank);let j=f==='gainG'?1:2;return a[j].loss<o.loss||a[j].rank<o.rank;}
function order(a,b){let s=$('sort').value;if(s==='id')return a.id.localeCompare(b.id);if(s==='roads'||s==='length')return C.gallery[b.scene][s]-C.gallery[a.scene][s]||a.i-b.i;if(s==='disagreement')return Number(match(b,'disagree'))-Number(match(a,'disagree'))||a.i-b.i;if(s.startsWith('rank'))return b.arms[+s.slice(4)].rank-a.arms[+s.slice(4)].rank||a.i-b.i;if(s.startsWith('score'))return a.arms[+s.slice(5)].positive-b.arms[+s.slice(5)].positive||a.i-b.i;return a.i-b.i;}
function apply(){Q=C.queries.filter(q=>match(q,$('filter').value)).sort(order);if(!Q.some(q=>q.i===current))current=Q[0]?.i??0;render();}
function image(obj,alt){return `<a href="${obj[$('map').value]}" target="_blank" rel="noopener"><img class="map" loading="lazy" src="${obj[$('map').value]}" alt="${esc(alt)}"></a>`;}
async function render(){const stamp=++token;if(!Q.length){$('query').innerHTML='<p class="empty">No queries match this filter.</p>';$('columns').innerHTML='';$('delta').innerHTML='';$('status').textContent='0 matching queries';return;}let q=C.queries[current],g=C.gallery[q.scene];let at=Q.findIndex(x=>x.i===current);$('status').textContent=`${at+1} / ${Q.length} filtered · query ${q.i+1} / 2000 · immutable selected vectors`;
 history.replaceState(null,'','#'+new URLSearchParams({q:q.id,filter:$('filter').value,sort:$('sort').value,depth:$('depth').value,map:$('map').value}));
 $('query').innerHTML=`<figure>${image(q,'Accepted augmented query roads')}<figcaption>Actual augmented query · view ${q.view+1}<br>${q.observed_roads} observed roads</figcaption></figure><figure>${image(g,'Unaugmented source scene')}<figcaption>Original source / positive gallery<br>${g.roads} parent roads</figcaption></figure><div class="meta"><h2>Query ${q.i+1}</h2><div class="id">${esc(q.id)}<br>${g.id}</div><p><span class="pill">${g.roads?'Road-nonempty':'ZERO ROAD'}</span><span class="pill">Count ${g.countbin}</span><span class="pill">Mean parent ${fmt(g.length,1)} m · ${g.lengthbin}</span><span class="pill">${match(q,'disagree')?'Rank-1 disagreement':'Rank-1 agreement'}</span></p><p>Road density: ${fmt(g.descriptors.road_density??0)}<br>Orientation dispersion: ${fmt(g.descriptors.road_orientation_dispersion??0)}<br>Original road-location dispersion: ${fmt(g.descriptors.road_location_dispersion??0)}</p><p class="details">Road support is identical across segmentation policies. Result panels are original gallery scenes. Click a map to enlarge.</p></div>`;
 $('delta').innerHTML='<table class="summary"><tr><th>Arm</th><th>Source rank / top-1</th><th>Source cosine</th><th>Best incorrect</th><th>Margin / Δ vs Original</th><th>Loss / Δ</th></tr>'+q.arms.map((a,i)=>`<tr><td>${C.arms[i].name}</td><td>${a.rank} · ${a.rank===1?'✓ correct':'incorrect'}<br><span class="id">${C.gallery[a.top].id}</span></td><td>${fmt(a.positive,6)}<br>Δ ${fmt(a.positive-q.arms[0].positive,6)}</td><td>${fmt(a.incorrect,6)}<br>${i?(a.incorrect>q.arms[0].incorrect?'closer':'farther')+' vs Original':''}</td><td>${fmt(a.margin,6)} / ${fmt(a.margin-q.arms[0].margin,6)}</td><td>${fmt(a.loss,6)} / ${fmt(a.loss-q.arms[0].loss,6)}</td></tr>`).join('')+'</table>';
 $('columns').innerHTML='<p>Loading aligned rankings…</p>';try{let r=await fetch(`queries/${q.i}.json`).then(x=>{if(!x.ok)throw Error(x.status);return x.json()});if(stamp!==token)return;let depth=$('depth').value;
 $('columns').innerHTML=C.arms.map((a,i)=>`<div><div class="arm-title"><h2>${a.name}</h2><small>Selected epoch ${a.epoch} · ${a.checkpoint_sha256.slice(0,12)}</small></div>`+r.arms[i].filter(x=>depth==='middle'?x[0]>=491&&x[0]<=500:depth==='lower'?x[0]>=991:x[0]<=Number(depth)).map(([rank,idx,score])=>{let v=C.gallery[idx],correct=idx===q.scene;return `<article class="card ${correct?'correct':''}"><div class="card-top"><strong>Rank ${rank}</strong><span>${fmt(score,6)} ${correct?'<span class="correct-label">✓ source</span>':''}</span></div>${image(v,'Rank '+rank+' '+v.id)}<div class="id">${v.id}</div><div class="details">${v.roads} roads · mean parent ${fmt(v.length,1)} m</div></article>`}).join('')+'</div>').join('');}catch(e){$('columns').textContent='Unable to load query: '+e.message;}}
function navigate(step){if(!Q.length)return;let i=Q.findIndex(q=>q.i===current);current=Q[(i+step+Q.length)%Q.length].i;render();}
async function init(){C=await fetch('catalog.json').then(x=>x.json());$('filter').innerHTML=filters.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');$('sort').innerHTML=sorts.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');let p=new URLSearchParams(location.hash.slice(1));for(let id of ['filter','sort','depth','map'])if([...$(id).options].some(o=>o.value===p.get(id)))$(id).value=p.get(id);current=C.queries.find(q=>q.id===p.get('q'))?.i??0;
 for(let id of ['filter','sort'])$(id).onchange=apply;for(let id of ['depth','map'])$(id).onchange=render;$('prev').onclick=()=>navigate(-1);$('next').onclick=()=>navigate(1);$('random').onclick=()=>{if(Q.length){current=Q[Math.floor(Math.random()*Q.length)].i;render()}};$('go').onclick=()=>{let s=$('jump').value.trim(),q=/^\d+$/.test(s)?C.queries[Number(s)-1]:C.queries.find(q=>q.id===s||C.gallery[q.scene].id===s);if(!q){$('status').textContent='Query not found';return;}$('filter').value='all';current=q.i;apply()};$('jump').onkeydown=e=>{if(e.key==='Enter')$('go').click()};
 $('presets').innerHTML=[['nonempty','Road-nonempty'],['count50','High road count'],['gainG','G gain candidates'],['gainP','Ppre gain candidates'],['gp','G ≠ Ppre top 10'],['failure','Rank failure cases'],['zero','Zero-road ties']].map(([v,t])=>`<button data-filter="${v}">${t}</button>`).join('');$('presets').onclick=e=>{if(e.target.dataset.filter){$('filter').value=e.target.dataset.filter;apply()}};apply();}
init().catch(e=>{$('status').textContent='Load failed: '+e.message;console.error(e)});
