list_research_model_dataloader <- list(
  tar_target(p6_model_dataloader_contract_files, p6_contract_files(), format = "file"),
  tar_target(d64_model_architecture_contract,
             p6_build_architecture(model_methodology_contract, reduced_methodology_authority,
                                   accepted_p3_dataset_acceptance_reference, augmentation_bank_acceptance,
                                   effective_augmentation_bank_index, fixed_query_acceptance,
                                   accepted_p2_base_spatial_reference,
                                   p6_model_dataloader_contract_files), format = "file"),
  tar_target(p6_preprocessing_contract,
             p6_build_preprocessing(accepted_p3_dataset_acceptance_reference, augmentation_bank_acceptance,
                                    effective_augmentation_bank_index, fixed_query_acceptance,
                                    reduced_methodology_authority, accepted_p2_base_spatial_reference,
                                    p6_model_dataloader_contract_files), format = "file"),
  tar_target(p6_dataloader_acceptance,
             p6_build_dataloader_acceptance(accepted_p3_dataset_acceptance_reference, augmentation_bank_acceptance,
                                            effective_augmentation_bank_index, fixed_query_acceptance,
                                            reduced_methodology_authority, accepted_p2_base_spatial_reference,
                                            p6_preprocessing_contract, p6_model_dataloader_contract_files), format = "file"),
  tar_target(d64_encoder_cpu_smoke,
             p6_build_cpu_smoke(accepted_p3_dataset_acceptance_reference, augmentation_bank_acceptance,
                                effective_augmentation_bank_index, fixed_query_acceptance,
                                reduced_methodology_authority, accepted_p2_base_spatial_reference,
                                p6_preprocessing_contract, d64_model_architecture_contract,
                                p6_dataloader_acceptance, p6_model_dataloader_contract_files), format = "file"),
  tar_target(model_data_acceptance,
             p6_final_acceptance(d64_model_architecture_contract, p6_dataloader_acceptance,
                                 d64_encoder_cpu_smoke, reduced_methodology_authority,
                                 accepted_p3_dataset_acceptance_reference, augmentation_bank_acceptance,
                                 effective_augmentation_bank_index, fixed_query_acceptance,
                                 accepted_p2_base_spatial_reference, p6_model_dataloader_contract_files),
             format = "file")
)
