retrieval_gallery_targets <- list(
  tar_target(retrieval_gallery_sources, retrieval_source_files(), format = "file"),
  tar_target(retrieval_gallery_pilot_evidence,
    Sys.getenv("FUSE_RETRIEVAL_PILOT_EVIDENCE", "/mnt/hdd002/dhnyu/fusedata/runtime/retrieval_gallery/approved_pilots.json"), format = "file"),
  tar_target(retrieval_gallery_authority,
    { retrieval_gallery_sources; retrieval_stage("authority", evidence = retrieval_gallery_pilot_evidence) }, format = "file"),
  tar_target(retrieval_gallery_scene_index,
    file.path(dirname(retrieval_gallery_authority), "index/supplemental_scene_index.parquet"), format = "file"),
  tar_target(retrieval_gallery_spatial_truth,
    { retrieval_gallery_scene_index; retrieval_stage("spatial", retrieval_gallery_authority) }, format = "file"),
  tar_target(retrieval_gallery_original_cache,
    retrieval_stage("cache", retrieval_gallery_spatial_truth), format = "file"),
  tar_target(retrieval_gallery_prepared_inputs,
    retrieval_stage("prepared", retrieval_gallery_original_cache), format = "file"),
  tar_target(retrieval_gallery_geometry,
    retrieval_stage("geometry", retrieval_gallery_prepared_inputs), format = "file",
    resources = tar_resources(crew = tar_resources_crew(controller = "retrieval_gpu_pair"))),
  tar_target(retrieval_gallery_embeddings,
    retrieval_stage("inference", retrieval_gallery_geometry), format = "file",
    resources = tar_resources(crew = tar_resources_crew(controller = "retrieval_gpu_pair"))),
  tar_target(retrieval_gallery_union,
    retrieval_stage("union", retrieval_gallery_embeddings), format = "file"),
  tar_target(retrieval_gallery_rankings,
    retrieval_stage("rankings", retrieval_gallery_union), format = "file"),
  tar_target(retrieval_gallery_inspector,
    retrieval_stage("inspector", retrieval_gallery_rankings), format = "file"),
  tar_target(retrieval_gallery_validation,
    retrieval_stage("validate", retrieval_gallery_inspector), format = "file"),
  tar_target(retrieval_gallery_acceptance,
    retrieval_stage("accept", retrieval_gallery_validation), format = "file")
)
