retrieval_gallery_targets <- list(
  tar_target(s12_gallery_sources, retrieval_source_files(), format = "file"),
  tar_target(i12_gallery_pilot_validation,
    Sys.getenv("FUSE_RETRIEVAL_PILOT_EVIDENCE", "/mnt/hdd002/dhnyu/fusedata/runtime/retrieval_gallery/approved_pilots.json"), format = "file"),
  tar_target(s12_gallery_authority,
    { s12_gallery_sources; retrieval_authority_bundle(i12_gallery_pilot_validation) }, format = "file"),
  tar_target(s12_gallery_spatial_cache,
    retrieval_stage("spatial", artifact_path(s12_gallery_authority, "supplemental_scene_index.parquet")), format = "file"),
  tar_target(s12_gallery_original_cache,
    retrieval_stage("cache", s12_gallery_spatial_cache), format = "file"),
  tar_target(s12_gallery_input_cache,
    retrieval_stage("prepared", s12_gallery_original_cache), format = "file"),
  tar_target(s12_gallery_geometry_cache,
    retrieval_stage("geometry", s12_gallery_input_cache), format = "file",
    resources = tar_resources(crew = tar_resources_crew(controller = "retrieval_gpu_pair"))),
  tar_target(s12_gallery_embedding_cache,
    retrieval_stage("inference", s12_gallery_geometry_cache), format = "file",
    resources = tar_resources(crew = tar_resources_crew(controller = "retrieval_gpu_pair"))),
  tar_target(s12_gallery_union_index,
    retrieval_stage("union", s12_gallery_embedding_cache), format = "file"),
  tar_target(s12_gallery_ranking_index,
    retrieval_stage("rankings", s12_gallery_union_index), format = "file"),
  tar_target(s12_gallery_inspector_index,
    retrieval_stage("inspector", s12_gallery_ranking_index), format = "file"),
  tar_target(s12_gallery_acceptance,
    retrieval_acceptance_bundle(s12_gallery_inspector_index), format = "file")
)
