list_s06_model_inputs <- list(
  tar_target(s06_dataset_sources, p6_contract_files(), format = "file"),
  tar_target(s06_reference_model_contract,
             p6_build_architecture(s00_model_methodology_contract, s00_methodology_authority,
                                   s03_scene_dataset_acceptance, s04_bank_acceptance,
                                   s04_bank_acceptance, s05_query_acceptance,
                                   s02_spatial_acceptance,
                                   s06_dataset_sources), format = "file"),
  tar_target(s06_dataset_preprocessing_contract,
             p6_build_preprocessing(s03_scene_dataset_acceptance, s04_bank_acceptance,
                                    s04_bank_acceptance, s05_query_acceptance,
                                    s00_methodology_authority, s02_spatial_acceptance,
                                    s06_dataset_sources), format = "file"),
  tar_target(s06_dataset_loader_acceptance,
             p6_build_dataloader_acceptance(s03_scene_dataset_acceptance, s04_bank_acceptance,
                                            s04_bank_acceptance, s05_query_acceptance,
                                            s00_methodology_authority, s02_spatial_acceptance,
                                            s06_dataset_preprocessing_contract, s06_dataset_sources), format = "file"),
  tar_target(s06_reference_encoder_validation,
             p6_build_cpu_smoke(s03_scene_dataset_acceptance, s04_bank_acceptance,
                                s04_bank_acceptance, s05_query_acceptance,
                                s00_methodology_authority, s02_spatial_acceptance,
                                s06_dataset_preprocessing_contract, s06_reference_model_contract,
                                s06_dataset_loader_acceptance, s06_dataset_sources), format = "file"),
  tar_target(s06_dataset_acceptance,
             p6_final_acceptance(s06_reference_model_contract, s06_dataset_loader_acceptance,
                                 s06_reference_encoder_validation, s00_methodology_authority,
                                 s03_scene_dataset_acceptance, s04_bank_acceptance,
                                 s04_bank_acceptance, s05_query_acceptance,
                                 s02_spatial_acceptance, s06_dataset_sources),
             format = "file")
)
