# S10 is not model selection and has no training/evaluation execution dependency.
list_s10_retrieval_visualization <- list(
  targets::tar_target(s10_retrieval_sources,
    s10_run("sources", "--config", s10_retrieval_contract),
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_contract, "config/retrieval_visualization.yml",
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_s09_acceptance,
    yaml::read_yaml(s10_retrieval_contract)$campaign,
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_parent_files,
    { s10_retrieval_s09_acceptance; s10_parent_files(s10_retrieval_contract) },
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_model_manifest,
    { s10_retrieval_sources; s10_retrieval_parent_files; s10_retrieval_s09_acceptance;
      s10_run("models", "--config", s10_retrieval_contract) },
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_gallery_manifest,
    s10_run("gallery", "--models", s10_manifest(s10_retrieval_model_manifest)),
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_query_manifest,
    s10_run("queries", "--models", s10_manifest(s10_retrieval_model_manifest),
      "--gallery", s10_manifest(s10_retrieval_gallery_manifest)),
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_model_id, s10_model_ids(s10_retrieval_model_manifest),
    iteration = "list", resources = s10_cpu),
  targets::tar_target(s10_retrieval_original_inputs,
    s10_run("originals", s10_common_args(s10_retrieval_model_manifest,
      s10_retrieval_gallery_manifest, s10_retrieval_query_manifest)),
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_embeddings,
    s10_run("embeddings", s10_common_args(s10_retrieval_model_manifest,
      s10_retrieval_gallery_manifest, s10_retrieval_query_manifest), "--model-id", s10_retrieval_model_id,
      "--prepared", s10_manifest(s10_retrieval_original_inputs)),
    pattern = map(s10_retrieval_model_id), format = "file", resources = s10_gpu),
  targets::tar_target(s10_retrieval_rankings,
    s10_run("rankings", s10_common_args(s10_retrieval_model_manifest,
      s10_retrieval_gallery_manifest, s10_retrieval_query_manifest),
      "--embedding", s10_manifest(s10_retrieval_embeddings)),
    pattern = map(s10_retrieval_embeddings), format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_scene_render_cache,
    s10_run("renders", s10_common_args(s10_retrieval_model_manifest,
      s10_retrieval_gallery_manifest, s10_retrieval_query_manifest),
      "--rankings", s10_rank_manifests(s10_retrieval_rankings)),
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_comparison_pages,
    s10_run("pages", s10_common_args(s10_retrieval_model_manifest,
      s10_retrieval_gallery_manifest, s10_retrieval_query_manifest),
      "--rankings", s10_rank_manifests(s10_retrieval_rankings),
      "--render", s10_manifest(s10_retrieval_scene_render_cache)),
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_summary,
    s10_run("summary", s10_common_args(s10_retrieval_model_manifest,
      s10_retrieval_gallery_manifest, s10_retrieval_query_manifest),
      "--rankings", s10_rank_manifests(s10_retrieval_rankings),
      "--pages", s10_manifest(s10_retrieval_comparison_pages)),
    format = "file", resources = s10_cpu),
  targets::tar_target(s10_retrieval_visualization_acceptance,
    s10_run("acceptance", s10_common_args(s10_retrieval_model_manifest,
      s10_retrieval_gallery_manifest, s10_retrieval_query_manifest),
      "--rankings", s10_rank_manifests(s10_retrieval_rankings),
      "--pages", s10_manifest(s10_retrieval_comparison_pages),
      "--summary", s10_manifest(s10_retrieval_summary)),
    format = "file", resources = s10_cpu)
)
